# No Bugs in Production (NBP)
# https://github.com/aenachescu/nbp
# 
# Licensed under the MIT License <http://opensource.org/licenses/MIT>.
# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 Alin Enachescu <https://github.com/aenachescu>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

language: c
sudo: required

matrix:
  include:
    #
    # gcc
    #
    - os: linux
      env:
        - DESCRIPTION="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gcc-6
            - gcc-7
            - gcc-8
            - gcc-9
            - lcov
      before_install:
        - gem install coveralls-lcov
      script:
        - cd build/LinuxMakefile

        # gcc 5
        - make clean
        - make all CC=gcc-5 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh && ./run_coveralls.sh
        # gcc 6
        - make clean
        - make all CC=gcc-6 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh
        # gcc 7
        - make clean
        - make all CC=gcc-7 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh
        # gcc 8
        - make clean
        - make all CC=gcc-8 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh
        # gcc 9
        - make clean
        - make all CC=gcc-9 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh

    #
    # g++
    #
    - os: linux
      env:
        - DESCRIPTION="linux g++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - g++-6
            - g++-7
            - g++-8
            - g++-9
            - lcov
      before_install:
        - gem install coveralls-lcov
      script:
        - cd build/LinuxMakefile

        # g++ 5
        - make clean
        - make all CC=g++-5 COMPILER_FLAG=-DNBP_COMPILER_GPP SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh && ./run_coveralls.sh
        # g++ 6
        - make clean
        - make all CC=g++-6 COMPILER_FLAG=-DNBP_COMPILER_GPP SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh
        # g++ 7
        - make clean
        - make all CC=g++-7 COMPILER_FLAG=-DNBP_COMPILER_GPP SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh
        # g++ 8
        - make clean
        - make all CC=g++-8 COMPILER_FLAG=-DNBP_COMPILER_GPP SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh
        # g++ 9
        - make clean
        - make all CC=g++-9 COMPILER_FLAG=-DNBP_COMPILER_GPP SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh

    #
    # clang
    #
    - os: linux
      env:
        - DESCRIPTION="linux clang"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
            - llvm-toolchain-xenial-8
          packages:
            - clang-7
            - clang-8
            - lcov
      before_install:
        - gem install coveralls-lcov
      script:
        - cd build/LinuxMakefile

        # clang 7
        - make clean
        - make all CC=clang-7 COMPILER_FLAG=-DNBP_COMPILER_CLANG SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh && ./run_coveralls.sh
        # clang 8
        - make clean
        - make all CC=clang-8 COMPILER_FLAG=-DNBP_COMPILER_CLANG SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - ./run_tests.sh

    #
    # gcc9 sanitizers
    #
    - os: linux
      env:
        - DESCRIPTION="linux gcc-9 sanitizers"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
      script:
        - cd build/LinuxMakefile

        # address
        - make clean
        - make all CC=gcc-9 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP GCOV_FLAGS= SANITIZERS="-g -fsanitize=address,pointer-compare,pointer-subtract"
        - ./run_tests.sh ASAN_OPTIONS="detect_invalid_pointer_pairs=1"
        - ./run_tests.sh ASAN_OPTIONS="detect_stack_use_after_return=1"

        # thread
        - make clean
        - make all CC=gcc-9 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP GCOV_FLAGS= SANITIZERS="-g -fsanitize=thread"
        - ./run_tests.sh

        # leak
        - make clean
        - make all CC=gcc-9 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP GCOV_FLAGS= SANITIZERS="-g -fsanitize=leak"
        - ./run_tests.sh

        # undefined behaviour
        - make clean
        - make all CC=gcc-9 COMPILER_FLAG=-DNBP_COMPILER_GCC SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP GCOV_FLAGS= SANITIZERS="-g -fsanitize=undefined,shift,integer-divide-by-zero,unreachable,vla-bound,null,return,signed-integer-overflow,bounds,bounds-strict,alignment,object-size,float-divide-by-zero,float-cast-overflow,nonnull-attribute,returns-nonnull-attribute,bool,enum,vptr,pointer-overflow,builtin -fuse-ld=gold"
        - ./run_tests.sh
