# No Bugs in Production (NBP)
# Copyright (C) 2019-present Alin Enachescu

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

language: c
sudo: required

matrix:
  include:
    #
    # gcc 5
    #
    - os: linux
      env:
        - TEST="gcc 5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      before_install:
        - pip install --user cpp-coveralls
      script:
        - make -C build/ clean
        - make -C build/ all CC=gcc-5
        - cd build
        - ./run_tests.sh
      after_success:
        - coveralls
          -r /home/travis/build/aenachescu/nbp
          -b /home/travis/build/aenachescu/nbp/build
          --gcov gcov --gcov-options '\-lp'

    #
    # g++ 5
    #
    - os: linux
      env:
        - TEST="g++ 5"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      before_install:
        - pip install --user cpp-coveralls
      script:
        - make -C build/ clean
        - make -C build/ all CC=g++-5
        - cd build
        - ./run_tests.sh
      after_success:
        - coveralls
          -r /home/travis/build/aenachescu/nbp
          -b /home/travis/build/aenachescu/nbp/build
          --gcov gcov --gcov-options '\-lp'
