# No Bugs in Production (NBP)
# Copyright (C) 2019-present Alin Enachescu

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

language: c
sudo: required

matrix:
  include:
    #
    # gcc
    #
    - os: linux
      env:
        - DESCRIPTION="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gcc-6
            - gcc-7
            - gcc-8
            - gcc-9
      before_install:
        - pip install --user cpp-coveralls
      script:
        # gcc 5
        - make -C build/ clean
        - make -C build/ all CC=gcc-5 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-5 && cd ..
        # gcc 6
        - make -C build/ clean
        - make -C build/ all CC=gcc-6 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-6 && cd ..
        # gcc 7
        - make -C build/ clean
        - make -C build/ all CC=gcc-7 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-7 && cd ..
        # gcc 8
        - make -C build/ clean
        - make -C build/ all CC=gcc-8 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-8 && cd ..
        # gcc 9
        - make -C build/ clean
        - make -C build/ all CC=gcc-9 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-9 && cd ..

    #
    # g++
    #
    - os: linux
      env:
        - DESCRIPTION="linux g++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - g++-6
            - g++-7
            - g++-8
            - g++-9
      before_install:
        - pip install --user cpp-coveralls
      script:
        # g++ 5
        - make -C build/ clean
        - make -C build/ all CC=g++-5 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-5 && cd ..
        # g++ 6
        - make -C build/ clean
        - make -C build/ all CC=g++-6 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-6 && cd ..
        # g++ 7
        - make -C build/ clean
        - make -C build/ all CC=g++-7 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-7 && cd ..
        # g++ 8
        - make -C build/ clean
        - make -C build/ all CC=g++-8 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-8 && cd ..
        # g++ 9
        - make -C build/ clean
        - make -C build/ all CC=g++-9 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        - cd build && ./run_coveralls.sh gcov-9 && cd ..
