# No Bugs in Production (NBP)
# https://github.com/aenachescu/nbp
# 
# Licensed under the MIT License <http://opensource.org/licenses/MIT>.
# SPDX-License-Identifier: MIT
# Copyright (c) 2019-2020 Alin Enachescu <https://github.com/aenachescu>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

language: c
sudo: required

matrix:
  include:
    #
    # gcc
    #
    - os: linux
      env:
        - DESCRIPTION="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gcc-6
            - gcc-7
            - gcc-8
            - gcc-9
      before_install:
        - gem install coveralls-lcov
      script:
        # install cmake 3.17
        - mkdir -p cmake-3.17 && wget -qO- "https://cmake.org/files/v3.17/cmake-3.17.1-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake-3.17
        - export PATH=`pwd`/cmake-3.17/bin:$PATH

        # install lcov 1.14
        - mkdir lcov
        - cd lcov
        - wget https://github.com/linux-test-project/lcov/archive/v1.14.tar.gz
        - tar xfvz v1.14.tar.gz
        - cd lcov-1.14
        - sudo make install
        - cd ../../

        - cd build/LinuxCMake

        # gcc 5
        - cmake . -DCOMPILER=gcc-5 -DCODE_COVERAGE=ON
        - make
        - ./run_tests.sh
        - ./run_coveralls.sh gcov-5
        - make clean
        # gcc 6
        - cmake . -DCOMPILER=gcc-6
        - make
        - ./run_tests.sh
        - make clean
        # gcc 7
        - cmake . -DCOMPILER=gcc-7
        - make
        - ./run_tests.sh
        - make clean
        # gcc 8
        - cmake . -DCOMPILER=gcc-8
        - make
        - ./run_tests.sh
        - make clean
        # gcc 9
        - cmake . -DCOMPILER=gcc-9
        - make
        - ./run_tests.sh
        - make clean

    #
    # g++
    #
    - os: linux
      env:
        - DESCRIPTION="linux g++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - g++-6
            - g++-7
            - g++-8
            - g++-9
      before_install:
        - gem install coveralls-lcov
      script:
        # install cmake 3.17
        - mkdir -p cmake-3.17 && wget -qO- "https://cmake.org/files/v3.17/cmake-3.17.1-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake-3.17
        - export PATH=`pwd`/cmake-3.17/bin:$PATH

        # install lcov 1.14
        - mkdir lcov
        - cd lcov
        - wget https://github.com/linux-test-project/lcov/archive/v1.14.tar.gz
        - tar xfvz v1.14.tar.gz
        - cd lcov-1.14
        - sudo make install
        - cd ../../

        - cd build/LinuxCMake

        # g++ 5
        - cmake . -DCOMPILER=g++-5 -DCOMPILER_FLAG=-DNBP_COMPILER_GPP -DCODE_COVERAGE=ON
        - make
        - ./run_tests.sh
        - ./run_coveralls.sh gcov-5
        - make clean
        # g++ 6
        - cmake . -DCOMPILER=g++-6 -DCOMPILER_FLAG=-DNBP_COMPILER_GPP
        - make
        - ./run_tests.sh
        - make clean
        # g++ 7
        - cmake . -DCOMPILER=g++-7 -DCOMPILER_FLAG=-DNBP_COMPILER_GPP
        - make
        - ./run_tests.sh
        - make clean
        # g++ 8
        - cmake . -DCOMPILER=g++-8 -DCOMPILER_FLAG=-DNBP_COMPILER_GPP
        - make
        - ./run_tests.sh
        - make clean
        # g++ 9
        - cmake . -DCOMPILER=g++-9 -DCOMPILER_FLAG=-DNBP_COMPILER_GPP
        - make
        - ./run_tests.sh
        - make clean

    #
    # clang
    #
    - os: linux
      env:
        - DESCRIPTION="linux clang"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
            - llvm-toolchain-xenial-8
          packages:
            - clang-7
            - clang-8
            - llvm-7
      before_install:
        - gem install coveralls-lcov
      script:
        # install cmake 3.17
        - mkdir -p cmake-3.17 && wget -qO- "https://cmake.org/files/v3.17/cmake-3.17.1-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake-3.17
        - export PATH=`pwd`/cmake-3.17/bin:$PATH

        # install lcov 1.14
        - mkdir lcov
        - cd lcov
        - wget https://github.com/linux-test-project/lcov/archive/v1.14.tar.gz
        - tar xfvz v1.14.tar.gz
        - cd lcov-1.14
        - sudo make install
        - cd ../../

        - cd build/LinuxCMake

        # clang 7
        - cmake . -DCOMPILER=clang-7 -DCOMPILER_FLAG=-DNBP_COMPILER_CLANG -DCODE_COVERAGE=ON
        - make
        - ./run_tests.sh
        - ./run_coveralls.sh `pwd`/gcov_clang_7.sh
        - make clean
        # clang 8
        - cmake . -DCOMPILER=clang-8 -DCOMPILER_FLAG=-DNBP_COMPILER_CLANG
        - make
        - ./run_tests.sh
        - make clean

    #
    # gcc9 sanitizers
    #
    - os: linux
      env:
        - DESCRIPTION="linux gcc-9 sanitizers"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
      script:
        - mkdir -p cmake-3.17 && wget -qO- "https://cmake.org/files/v3.17/cmake-3.17.1-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake-3.17
        - export PATH=`pwd`/cmake-3.17/bin:$PATH

        - cd build/LinuxCMake

        # address
        - cmake . -DCOMPILER=gcc-9 -DADDRESS_SANITIZER=ON
        - make
        - ./run_tests.sh ASAN_OPTIONS="detect_invalid_pointer_pairs=1"
        - ./run_tests.sh ASAN_OPTIONS="detect_stack_use_after_return=1"
        - make clean

        # thread
        - cmake . -DCOMPILER=gcc-9 -DTHREAD_SANITIZER=ON
        - make
        - ./run_tests.sh
        - make clean

        # leak
        - cmake . -DCOMPILER=gcc-9 -DLEAK_SANITIZER=ON
        - make
        - ./run_tests.sh
        - make clean

        # undefined behaviour
        - cmake . -DCOMPILER=gcc-9 -DUNDEFINED_BEHAVIOR_SANITIZER=ON
        - make
        - ./run_tests.sh
        - make clean
