language: c
compiler: gcc
sudo: required

matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - pip install --user cpp-coveralls

script:
  - make -C build/ clean
  - make -C build/ all
  - ./build/basic_sample
  - ./build/modules_sample
  - ./build/modules_one_file_sample
  - ./build/submodules_sample
  - ./build/submodules_one_file_sample

after_success:
    - coveralls
        -r /home/travis/build/aenachescu/nbp
        -b /home/travis/build/aenachescu/nbp/build
        --gcov gcov --gcov-options '\-lp'