# No Bugs in Production (NBP)
# Copyright (C) 2019-present Alin Enachescu

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

language: c
sudo: required

matrix:
  include:
    #
    # gcc
    #
    - os: linux
      env:
        - DESCRIPTION="linux gcc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gcc-6
            - gcc-7
            - gcc-8
            - gcc-9
            - lcov
      before_install:
        - gem install coveralls-lcov
      script:
        # gcc 5
        - make -C build/ clean
        - make -C build/ all CC=gcc-5 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && ./run_coveralls.sh && cd ..
        # gcc 6
        - make -C build/ clean
        - make -C build/ all CC=gcc-6 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        # gcc 7
        - make -C build/ clean
        - make -C build/ all CC=gcc-7 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        # gcc 8
        - make -C build/ clean
        - make -C build/ all CC=gcc-8 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        # gcc 9
        - make -C build/ clean
        - make -C build/ all CC=gcc-9 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..

    #
    # g++
    #
    - os: linux
      env:
        - DESCRIPTION="linux g++"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - g++-6
            - g++-7
            - g++-8
            - g++-9
            - lcov
      before_install:
        - gem install coveralls-lcov
      script:
        # g++ 5
        - make -C build/ clean
        - make -C build/ all CC=g++-5 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && ./run_coveralls.sh && cd ..
        # g++ 6
        - make -C build/ clean
        - make -C build/ all CC=g++-6 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        # g++ 7
        - make -C build/ clean
        - make -C build/ all CC=g++-7 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        # g++ 8
        - make -C build/ clean
        - make -C build/ all CC=g++-8 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..
        # g++ 9
        - make -C build/ clean
        - make -C build/ all CC=g++-9 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..

    #
    # clang
    #
    - os: linux
      env:
        - DESCRIPTION="linux clang"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
            - llvm-toolchain-xenial-8
          packages:
            - clang-7
            - clang-8
            - lcov
      before_install:
        - gem install coveralls-lcov
      script:
        # clang 7
        - make -C build/ clean
        - make -C build/ all CC=clang-7 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && ./run_coveralls.sh && cd ..
        # clang 8
        - make -C build/ clean
        - make -C build/ all CC=clang-8 SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
        - cd build && ./run_tests.sh && cd ..

    #
    # gcc9 sanitizers
    #
    - os: linux
      env:
        - DESCRIPTION="linux gcc-9 sanitizers"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
      script:
        # address
        - make -C build/ clean
        - >
          make -C build/ all
            CC=gcc-9
            SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
            SANITIZERS="-fsanitize=address"
        - cd build && ./run_tests.sh && cd ..

        # pointer compare
        - make -C build/ clean
        - >
          make -C build/ all
            CC=gcc-9
            SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
            SANITIZERS="-fsanitize=pointer-compare"
        - cd build && ./run_tests.sh && cd ..

        # pointer substract
        - make -C build/ clean
        - >
          make -C build/ all
            CC=gcc-9
            SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
            SANITIZERS="-fsanitize=pointer-subtract"
        - cd build && ./run_tests.sh && cd ..

        # thread
        - make -C build/ clean
        - >
          make -C build/ all
            CC=gcc-9
            SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
            SANITIZERS="-fsanitize=thread"
        - cd build && ./run_tests.sh && cd ..

        # leak
        - make -C build/ clean
        - >
          make -C build/ all
            CC=gcc-9
            SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
            SANITIZERS="-fsanitize=leak"
        - cd build && ./run_tests.sh && cd ..

        # undefined behaviour
        - make -C build/ clean
        - >
          make -C build/ all
            CC=gcc-9
            SAMPLE_FLAGS=-DSAMPLE_DISABLE_SLEEP
            SANITIZERS="-fsanitize=undefined"
        - cd build && ./run_tests.sh && cd ..
